CREATE TABLE users
(
    id                NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    updated_datetime  TIMESTAMP                                      NOT NULL,
    created_datetime  TIMESTAMP                                      NOT NULL,
    provider_type     VARCHAR2(255)                                  NOT NULL,
    user_role         VARCHAR2(255)                                  NOT NULL,
    provider_user_id  VARCHAR2(255),
    email             VARCHAR2(255),
    password          VARCHAR2(255),
    signup_state      NUMBER(5)                                      NOT NULL,
    fcm_token         VARCHAR2(255),
    nickname          VARCHAR2(24),
    gender            VARCHAR2(255),
    profile_file_name VARCHAR2(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_fcmtoken UNIQUE (fcm_token);

ALTER TABLE users
    ADD CONSTRAINT uc_users_nickname UNIQUE (nickname);
