CREATE TABLE user_auth_identities
(
    id               NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_datetime TIMESTAMP                                      NOT NULL,
    user_id          NUMBER(38, 0)                                  NOT NULL,
    provider_type    VARCHAR2(255)                                  NOT NULL,
    provider_user_id VARCHAR2(255)                                  NOT NULL,
    CONSTRAINT pk_user_auth_identities PRIMARY KEY (id),
    CONSTRAINT fk_user_auth_identities_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uc_auth_identity_provider_user UNIQUE (provider_type, provider_user_id),
    CONSTRAINT uc_auth_identity_user_provider UNIQUE (user_id, provider_type)
);
