-- Existing installations only. Back up the users table before applying this migration.
DECLARE
    missing_identity_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO missing_identity_count
    FROM users
    WHERE provider_user_id IS NULL;

    IF missing_identity_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Firebase UID가 없는 기존 사용자의 provider_user_id를 먼저 backfill해야 합니다.');
    END IF;
END;
/

CREATE TABLE user_auth_identities
(
    id               NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_datetime TIMESTAMP                                      NOT NULL,
    user_id          NUMBER(38, 0)                                  NOT NULL,
    provider_type    VARCHAR2(255)                                  NOT NULL,
    provider_user_id VARCHAR2(255)                                  NOT NULL,
    CONSTRAINT pk_user_auth_identities PRIMARY KEY (id),
    CONSTRAINT fk_user_auth_identities_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uc_auth_identity_provider_user UNIQUE (provider_type, provider_user_id),
    CONSTRAINT uc_auth_identity_user_provider UNIQUE (user_id, provider_type)
);

INSERT INTO user_auth_identities (created_datetime, user_id, provider_type, provider_user_id)
SELECT CURRENT_TIMESTAMP, id, provider_type, provider_user_id
FROM users
WHERE provider_user_id IS NOT NULL;

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE users DROP CONSTRAINT uc_users_provider';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN
            RAISE;
        END IF;
END;
/

ALTER TABLE users DROP (provider_type, provider_user_id, password);
