CREATE TABLE tour_classification_codes (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level1_code VARCHAR2(2 CHAR) NOT NULL,
    level1_name VARCHAR2(100 CHAR) NOT NULL,
    level2_code VARCHAR2(4 CHAR) NOT NULL,
    level2_name VARCHAR2(100 CHAR) NOT NULL,
    level3_code VARCHAR2(8 CHAR) NOT NULL,
    level3_name VARCHAR2(100 CHAR) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    updated_datetime TIMESTAMP NOT NULL,
    CONSTRAINT uk_tour_classification_level3 UNIQUE (level3_code)
);

CREATE INDEX ix_tour_classification_levels ON tour_classification_codes(level1_code, level2_code);
