CREATE TABLE tourism_contents (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id NUMBER(19) NOT NULL,
    content_type_id NUMBER(3) NOT NULL,
    title VARCHAR2(300 CHAR) NOT NULL,
    address1 VARCHAR2(500 CHAR),
    address2 VARCHAR2(500 CHAR),
    zipcode VARCHAR2(10 CHAR),
    telephone VARCHAR2(300 CHAR),
    first_image_url VARCHAR2(1000 CHAR),
    first_thumbnail_url VARCHAR2(1000 CHAR),
    copyright_type VARCHAR2(20 CHAR),
    longitude FLOAT(53),
    latitude FLOAT(53),
    map_level VARCHAR2(10 CHAR),
    source_created_datetime TIMESTAMP,
    source_modified_datetime TIMESTAMP,
    region_code VARCHAR2(2 CHAR),
    signgu_code VARCHAR2(3 CHAR),
    level1_code VARCHAR2(3 CHAR),
    level2_code VARCHAR2(5 CHAR),
    level3_code VARCHAR2(9 CHAR),
    created_datetime TIMESTAMP NOT NULL,
    updated_datetime TIMESTAMP NOT NULL,
    CONSTRAINT uk_tourism_content_id UNIQUE (content_id)
);

CREATE INDEX ix_tourism_content_type ON tourism_contents(content_type_id);
CREATE INDEX ix_tourism_content_region ON tourism_contents(region_code, signgu_code);
CREATE INDEX ix_tourism_content_classification ON tourism_contents(level1_code, level2_code, level3_code);
