CREATE TABLE tourism_content_details (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tourism_content_id NUMBER(19) NOT NULL,
    intro_payload CLOB NOT NULL,
    info_payload CLOB NOT NULL,
    content_image_payload CLOB NOT NULL,
    menu_image_payload CLOB NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    updated_datetime TIMESTAMP NOT NULL,
    CONSTRAINT uk_tourism_content_detail UNIQUE (tourism_content_id),
    CONSTRAINT fk_tourism_content_detail FOREIGN KEY (tourism_content_id)
        REFERENCES tourism_contents(id) ON DELETE CASCADE
);
