CREATE TABLE notifications (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id NUMBER(19) NOT NULL,
    notification_type VARCHAR2(40 CHAR) NOT NULL,
    content VARCHAR2(500 CHAR) NOT NULL,
    chat_room_id NUMBER(19),
    reference_id NUMBER(19) NOT NULL,
    read_datetime TIMESTAMP,
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_notification_recipient FOREIGN KEY (recipient_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_chat_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms(id) ON DELETE CASCADE,
    CONSTRAINT uk_notification_reference UNIQUE (recipient_id, notification_type, reference_id),
    CONSTRAINT ck_notification_type CHECK (
        notification_type IN (
            'CHAT_ROOM_CREATED',
            'CHAT_MESSAGE_RECEIVED',
            'RECRUITMENT_DEADLINE',
            'FRIEND_REQUEST',
            'FEED_LIKE'
        )
    )
);

CREATE INDEX ix_notification_recipient_id ON notifications(recipient_id, id);
CREATE INDEX ix_notification_unread ON notifications(recipient_id, read_datetime, id);
