CREATE TABLE users
(
    id                NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_datetime  TIMESTAMP(6)                                  NOT NULL,
    updated_datetime  TIMESTAMP(6)                                  NOT NULL,
    user_role         VARCHAR2(255)                                  NOT NULL,
    email             VARCHAR2(255),
    signup_state      VARCHAR2(255)                                  NOT NULL,
    fcm_token         VARCHAR2(255),
    nickname          VARCHAR2(24),
    gender            VARCHAR2(255),
    profile_file_name VARCHAR2(255),
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_fcm_token UNIQUE (fcm_token),
    CONSTRAINT uk_users_nickname UNIQUE (nickname),
    CONSTRAINT ck_users_role CHECK (user_role IN ('ROLE_USER', 'ROLE_ADMIN')),
    CONSTRAINT ck_users_signup_state CHECK (signup_state IN ('USER_INFO_REQUIRED', 'SIGNUP_COMPLETE')),
    CONSTRAINT ck_users_gender CHECK (gender IN ('M', 'F', 'N'))
);

CREATE TABLE user_auth_identities
(
    id                NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_datetime  TIMESTAMP(6)                                  NOT NULL,
    user_id           NUMBER(19, 0)                                 NOT NULL,
    provider_type     VARCHAR2(255)                                  NOT NULL,
    provider_user_id  VARCHAR2(255)                                  NOT NULL,
    CONSTRAINT pk_user_auth_identities PRIMARY KEY (id),
    CONSTRAINT fk_auth_identity_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_auth_provider_subject UNIQUE (provider_type, provider_user_id),
    CONSTRAINT uk_auth_user_provider UNIQUE (user_id, provider_type),
    CONSTRAINT ck_auth_provider CHECK (provider_type IN ('EMAIL', 'KAKAO', 'APPLE'))
);
