CREATE TABLE tourism_content_images (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tourism_content_id NUMBER(19) NOT NULL,
    image_type VARCHAR2(20 CHAR) NOT NULL,
    image_name VARCHAR2(500 CHAR),
    original_image_url VARCHAR2(1000 CHAR),
    serial_number VARCHAR2(100 CHAR),
    copyright_type VARCHAR2(20 CHAR),
    created_datetime TIMESTAMP NOT NULL,
    updated_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_tourism_content_image_content FOREIGN KEY (tourism_content_id)
        REFERENCES tourism_contents(id) ON DELETE CASCADE,
    CONSTRAINT ck_tourism_content_image_type CHECK (image_type IN ('CONTENT', 'MENU'))
);

CREATE INDEX ix_tourism_content_image_content_type
    ON tourism_content_images(tourism_content_id, image_type, id);

INSERT INTO tourism_content_images (
    tourism_content_id,
    image_type,
    image_name,
    original_image_url,
    serial_number,
    copyright_type,
    created_datetime,
    updated_datetime
)
SELECT
    detail.tourism_content_id,
    'CONTENT',
    image.image_name,
    image.original_image_url,
    image.serial_number,
    image.copyright_type,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM tourism_content_details detail,
    JSON_TABLE(
        detail.content_image_payload,
        '$[*]' COLUMNS (
            image_name VARCHAR2(500 CHAR) PATH '$.imgname',
            original_image_url VARCHAR2(1000 CHAR) PATH '$.originimgurl',
            serial_number VARCHAR2(100 CHAR) PATH '$.serialnum',
            copyright_type VARCHAR2(20 CHAR) PATH '$.cpyrhtDivCd'
        )
    ) image;

INSERT INTO tourism_content_images (
    tourism_content_id,
    image_type,
    image_name,
    original_image_url,
    serial_number,
    copyright_type,
    created_datetime,
    updated_datetime
)
SELECT
    detail.tourism_content_id,
    'MENU',
    image.image_name,
    image.original_image_url,
    image.serial_number,
    image.copyright_type,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM tourism_content_details detail,
    JSON_TABLE(
        detail.menu_image_payload,
        '$[*]' COLUMNS (
            image_name VARCHAR2(500 CHAR) PATH '$.imgname',
            original_image_url VARCHAR2(1000 CHAR) PATH '$.originimgurl',
            serial_number VARCHAR2(100 CHAR) PATH '$.serialnum',
            copyright_type VARCHAR2(20 CHAR) PATH '$.cpyrhtDivCd'
        )
    ) image;

DROP TABLE tourism_content_details CASCADE CONSTRAINTS;

ALTER TABLE tourism_contents RENAME COLUMN first_image_url TO thumbnail;
ALTER TABLE tourism_contents DROP COLUMN first_thumbnail_url;
