ALTER TABLE travel_courses ADD (
    description VARCHAR2(500 CHAR),
    duration_minutes NUMBER(10),
    trip_nights NUMBER(10),
    trip_days NUMBER(10)
);

ALTER TABLE travel_courses ADD CONSTRAINT ck_travel_course_duration CHECK (
    (duration_minutes IS NOT NULL AND trip_nights IS NULL AND trip_days IS NULL) OR
    (duration_minutes IS NULL AND trip_nights IS NOT NULL AND trip_days IS NOT NULL) OR
    (duration_minutes IS NULL AND trip_nights IS NULL AND trip_days IS NULL)
);

ALTER TABLE travel_course_places ADD (
    day_number NUMBER(3) DEFAULT 1 NOT NULL,
    visit_time TIMESTAMP
);

ALTER TABLE travel_course_places DROP CONSTRAINT uk_travel_place_sequence;
ALTER TABLE travel_course_places ADD CONSTRAINT uk_travel_place_day_sequence
    UNIQUE (travel_course_id, day_number, place_sequence);

ALTER TABLE travel_course_places ADD CONSTRAINT ck_travel_place_day_number
    CHECK (day_number >= 1);

ALTER TABLE chat_rooms ADD meeting_details VARCHAR2(500 CHAR);

CREATE TABLE travel_course_tags (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(30 CHAR) NOT NULL,
    CONSTRAINT uk_travel_course_tag_name UNIQUE (name)
);

INSERT INTO travel_course_tags (name) VALUES ('섬');
INSERT INTO travel_course_tags (name) VALUES ('트래킹');
INSERT INTO travel_course_tags (name) VALUES ('바다');
INSERT INTO travel_course_tags (name) VALUES ('자연');
INSERT INTO travel_course_tags (name) VALUES ('역사');
INSERT INTO travel_course_tags (name) VALUES ('체험');
INSERT INTO travel_course_tags (name) VALUES ('힐링');
INSERT INTO travel_course_tags (name) VALUES ('산책');

CREATE TABLE travel_course_tag_mappings (
    travel_course_id NUMBER(19) NOT NULL,
    tag_id NUMBER(19) NOT NULL,
    CONSTRAINT pk_travel_course_tag_mapping PRIMARY KEY (travel_course_id, tag_id),
    CONSTRAINT fk_course_tag_mapping_course FOREIGN KEY (travel_course_id)
        REFERENCES travel_courses(id) ON DELETE CASCADE,
    CONSTRAINT fk_course_tag_mapping_tag FOREIGN KEY (tag_id)
        REFERENCES travel_course_tags(id)
);

CREATE TABLE travel_course_ratings (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_course_id NUMBER(19) NOT NULL,
    chat_room_id NUMBER(19) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    score NUMBER(1) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    updated_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_course_rating_course FOREIGN KEY (travel_course_id) REFERENCES travel_courses(id) ON DELETE CASCADE,
    CONSTRAINT fk_course_rating_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms(id) ON DELETE CASCADE,
    CONSTRAINT fk_course_rating_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_course_rating_room_user UNIQUE (chat_room_id, user_id),
    CONSTRAINT ck_course_rating_score CHECK (score BETWEEN 1 AND 5)
);

CREATE INDEX ix_course_rating_course ON travel_course_ratings(travel_course_id);

ALTER TABLE notifications DROP CONSTRAINT ck_notification_type;
ALTER TABLE notifications ADD CONSTRAINT ck_notification_type CHECK (
    notification_type IN (
        'CHAT_ROOM_CREATED',
        'CHAT_MESSAGE_RECEIVED',
        'TRAVEL_COURSE_UPDATED',
        'MEETING_INFO_UPDATED',
        'RECRUITMENT_DEADLINE',
        'FRIEND_REQUEST',
        'FEED_LIKE',
        'MARKETING'
    )
);

CREATE TABLE notification_settings (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19) NOT NULL,
    chat_message_enabled NUMBER(1) DEFAULT 1 NOT NULL,
    recruitment_deadline_enabled NUMBER(1) DEFAULT 1 NOT NULL,
    social_activity_enabled NUMBER(1) DEFAULT 1 NOT NULL,
    marketing_enabled NUMBER(1) DEFAULT 1 NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    updated_datetime TIMESTAMP NOT NULL,
    CONSTRAINT uk_notification_setting_user UNIQUE (user_id),
    CONSTRAINT fk_notification_setting_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT ck_notification_setting_chat CHECK (chat_message_enabled IN (0, 1)),
    CONSTRAINT ck_notification_setting_deadline CHECK (recruitment_deadline_enabled IN (0, 1)),
    CONSTRAINT ck_notification_setting_social CHECK (social_activity_enabled IN (0, 1)),
    CONSTRAINT ck_notification_setting_marketing CHECK (marketing_enabled IN (0, 1))
);

INSERT INTO notification_settings (
    user_id,
    chat_message_enabled,
    recruitment_deadline_enabled,
    social_activity_enabled,
    marketing_enabled,
    created_datetime,
    updated_datetime
)
SELECT
    users.id,
    1,
    1,
    1,
    1,
    SYSTIMESTAMP,
    SYSTIMESTAMP
FROM users;
