CREATE TABLE chat_room_favorites (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19) NOT NULL,
    chat_room_id NUMBER(19) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_room_favorite_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_room_favorite_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms(id) ON DELETE CASCADE,
    CONSTRAINT uk_chat_room_favorite_user_room UNIQUE (user_id, chat_room_id)
);

CREATE INDEX ix_chat_room_favorite_room ON chat_room_favorites(chat_room_id);
