CREATE TABLE chat_room_kick_histories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id NUMBER NOT NULL,
    room_title VARCHAR2(100 CHAR) NOT NULL,
    kicked_user_id NUMBER NOT NULL,
    kicked_by_id NUMBER NOT NULL,
    reason VARCHAR2(500 CHAR) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_chat_kick_kicked_user FOREIGN KEY (kicked_user_id) REFERENCES users(id),
    CONSTRAINT fk_chat_kick_kicked_by FOREIGN KEY (kicked_by_id) REFERENCES users(id)
);

CREATE INDEX ix_chat_kick_user_created
    ON chat_room_kick_histories(kicked_user_id, created_datetime DESC, id DESC);
