ALTER TABLE chat_messages ADD (
    image_url VARCHAR2(1000 CHAR),
    tourism_content_id NUMBER(19),
    shared_latitude FLOAT(53),
    shared_longitude FLOAT(53),
    location_name VARCHAR2(100 CHAR),
    poll_anonymous NUMBER(1)
);

ALTER TABLE chat_messages ADD CONSTRAINT fk_chat_message_tourism_content
    FOREIGN KEY (tourism_content_id) REFERENCES tourism_contents(id);
ALTER TABLE chat_messages ADD CONSTRAINT ck_chat_message_poll_anonymous
    CHECK (poll_anonymous IN (0, 1));

DECLARE
    constraint_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO constraint_count
    FROM user_constraints
    WHERE table_name = 'CHAT_MESSAGES'
      AND constraint_name = 'CK_CHAT_MESSAGE_TYPE';
    IF constraint_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE chat_messages DROP CONSTRAINT ck_chat_message_type';
    END IF;
END;
/
ALTER TABLE chat_messages ADD CONSTRAINT ck_chat_message_type CHECK (
    message_type IN ('USER', 'SYSTEM', 'IMAGE', 'TOURISM_CONTENT', 'LOCATION', 'POLL', 'SETTLEMENT_MEMO')
);
DECLARE
    constraint_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO constraint_count
    FROM user_constraints
    WHERE table_name = 'CHAT_MESSAGES'
      AND constraint_name = 'CK_CHAT_MESSAGE_SENDER';
    IF constraint_count > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE chat_messages DROP CONSTRAINT ck_chat_message_sender';
    END IF;
END;
/
ALTER TABLE chat_messages ADD CONSTRAINT ck_chat_message_sender CHECK (
    (message_type = 'SYSTEM' AND sender_id IS NULL) OR
    (message_type <> 'SYSTEM' AND sender_id IS NOT NULL)
);

CREATE TABLE chat_poll_options (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id NUMBER(19) NOT NULL,
    option_text VARCHAR2(100 CHAR) NOT NULL,
    option_sequence NUMBER(10) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_chat_poll_option_message FOREIGN KEY (message_id) REFERENCES chat_messages(id) ON DELETE CASCADE,
    CONSTRAINT uk_chat_poll_option_sequence UNIQUE (message_id, option_sequence)
);

CREATE TABLE chat_poll_votes (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id NUMBER(19) NOT NULL,
    option_id NUMBER(19) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_chat_poll_vote_message FOREIGN KEY (message_id) REFERENCES chat_messages(id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_poll_vote_option FOREIGN KEY (option_id) REFERENCES chat_poll_options(id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_poll_vote_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_chat_poll_vote_message_user UNIQUE (message_id, user_id)
);

CREATE INDEX ix_chat_poll_votes_message ON chat_poll_votes(message_id);
