CREATE TABLE chat_room_notification_settings (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19) NOT NULL,
    chat_room_id NUMBER(19) NOT NULL,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    updated_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_chat_room_notification_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_room_notification_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms(id) ON DELETE CASCADE,
    CONSTRAINT uk_chat_room_notification_user_room UNIQUE (user_id, chat_room_id),
    CONSTRAINT ck_chat_room_notification_enabled CHECK (enabled IN (0, 1))
);
