ALTER TABLE users
    ADD (profile_image_generation_count NUMBER(1, 0) DEFAULT 0 NOT NULL);

ALTER TABLE users
    ADD CONSTRAINT ck_users_profile_image_generation_count
        CHECK (profile_image_generation_count BETWEEN 0 AND 3);

ALTER TABLE users
    DROP CONSTRAINT ck_users_signup_state;

ALTER TABLE users
    ADD CONSTRAINT ck_users_signup_state
        CHECK (signup_state IN ('USER_INFO_REQUIRED', 'PROFILE_IMAGE_REQUIRED', 'SIGNUP_COMPLETE'));

UPDATE users
SET signup_state = 'PROFILE_IMAGE_REQUIRED'
WHERE signup_state = 'SIGNUP_COMPLETE'
  AND nickname IS NOT NULL
  AND profile_file_name IS NULL;

CREATE TABLE user_profile_images
(
    id               NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_datetime TIMESTAMP(6)                                  NOT NULL,
    user_id          NUMBER(19, 0)                                 NOT NULL,
    file_name        VARCHAR2(255)                                  NOT NULL,
    CONSTRAINT pk_user_profile_images PRIMARY KEY (id),
    CONSTRAINT fk_profile_image_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_profile_image_file_name UNIQUE (file_name)
);

CREATE INDEX ix_profile_images_user_created
    ON user_profile_images (user_id, created_datetime);

INSERT INTO user_profile_images (created_datetime, user_id, file_name)
SELECT updated_datetime, id, profile_file_name
FROM users
WHERE profile_image_generation_count > 0
  AND profile_file_name IS NOT NULL;
