CREATE TABLE user_follows (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id NUMBER(19) NOT NULL,
    following_id NUMBER(19) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_follow_follower FOREIGN KEY (follower_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_follow_following FOREIGN KEY (following_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_user_follow_follower_following UNIQUE (follower_id, following_id),
    CONSTRAINT ck_user_follow_not_self CHECK (follower_id <> following_id)
);

CREATE INDEX ix_user_follows_following ON user_follows(following_id, created_datetime DESC);
CREATE INDEX ix_user_follows_follower ON user_follows(follower_id, created_datetime DESC);

CREATE TABLE travel_styles (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (START WITH 13) PRIMARY KEY,
    label VARCHAR2(30 CHAR) NOT NULL,
    CONSTRAINT uk_travel_styles_label UNIQUE (label)
);

INSERT ALL
    INTO travel_styles (id, label) VALUES (1, '자연')
    INTO travel_styles (id, label) VALUES (2, '사진')
    INTO travel_styles (id, label) VALUES (3, '바다')
    INTO travel_styles (id, label) VALUES (4, '산')
    INTO travel_styles (id, label) VALUES (5, '트레킹')
    INTO travel_styles (id, label) VALUES (6, '캠핑')
    INTO travel_styles (id, label) VALUES (7, '맛집')
    INTO travel_styles (id, label) VALUES (8, '카페')
    INTO travel_styles (id, label) VALUES (9, '역사·문화')
    INTO travel_styles (id, label) VALUES (10, '힐링')
    INTO travel_styles (id, label) VALUES (11, '액티비티')
    INTO travel_styles (id, label) VALUES (12, '축제')
SELECT 1 FROM DUAL;

ALTER TABLE user_travel_styles DROP CONSTRAINT ck_user_travel_style;
ALTER TABLE user_travel_styles DROP CONSTRAINT pk_user_travel_styles;
ALTER TABLE user_travel_styles ADD travel_style_id NUMBER(19);
UPDATE user_travel_styles uts
SET travel_style_id = CASE uts.travel_style
    WHEN 'NATURE' THEN 1
    WHEN 'PHOTOGRAPHY' THEN 2
    WHEN 'SEA' THEN 3
    WHEN 'MOUNTAIN' THEN 4
    WHEN 'TREKKING' THEN 5
    WHEN 'CAMPING' THEN 6
    WHEN 'FOOD' THEN 7
    WHEN 'CAFE' THEN 8
    WHEN 'HISTORY_CULTURE' THEN 9
    WHEN 'HEALING' THEN 10
    WHEN 'ACTIVITY' THEN 11
    WHEN 'FESTIVAL' THEN 12
END;
ALTER TABLE user_travel_styles MODIFY travel_style_id NOT NULL;
ALTER TABLE user_travel_styles DROP COLUMN travel_style;
ALTER TABLE user_travel_styles ADD CONSTRAINT fk_user_travel_style_style
    FOREIGN KEY (travel_style_id) REFERENCES travel_styles(id);
ALTER TABLE user_travel_styles ADD CONSTRAINT pk_user_travel_styles
    PRIMARY KEY (user_id, travel_style_id);
