CREATE TABLE feeds (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id NUMBER(19) NOT NULL,
    chat_room_id NUMBER(19) NOT NULL,
    title VARCHAR2(100 CHAR) NOT NULL,
    content VARCHAR2(500 CHAR) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_feed_author FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_feed_chat_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms(id) ON DELETE CASCADE,
    CONSTRAINT uk_feed_room_author UNIQUE (chat_room_id, author_id)
);

CREATE INDEX ix_feeds_created ON feeds(created_datetime DESC);
CREATE INDEX ix_feeds_author_created ON feeds(author_id, created_datetime DESC);

CREATE TABLE feed_images (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_id NUMBER(19) NOT NULL,
    file_name VARCHAR2(1000 CHAR) NOT NULL,
    image_sequence NUMBER(10) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_feed_image_feed FOREIGN KEY (feed_id) REFERENCES feeds(id) ON DELETE CASCADE,
    CONSTRAINT uk_feed_image_sequence UNIQUE (feed_id, image_sequence)
);

CREATE TABLE feed_likes (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_id NUMBER(19) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_feed_like_feed FOREIGN KEY (feed_id) REFERENCES feeds(id) ON DELETE CASCADE,
    CONSTRAINT fk_feed_like_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_feed_like_feed_user UNIQUE (feed_id, user_id)
);

CREATE INDEX ix_feed_likes_user ON feed_likes(user_id);

CREATE TABLE feed_comments (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_id NUMBER(19) NOT NULL,
    author_id NUMBER(19) NOT NULL,
    parent_comment_id NUMBER(19),
    content VARCHAR2(500 CHAR) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_feed_comment_feed FOREIGN KEY (feed_id) REFERENCES feeds(id) ON DELETE CASCADE,
    CONSTRAINT fk_feed_comment_author FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_feed_comment_parent FOREIGN KEY (parent_comment_id) REFERENCES feed_comments(id) ON DELETE CASCADE
);

CREATE INDEX ix_feed_comments_feed_created ON feed_comments(feed_id, created_datetime);
CREATE INDEX ix_feed_comments_parent ON feed_comments(parent_comment_id);
