CREATE TABLE travel_companions (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id NUMBER(19) NOT NULL,
    companion_id NUMBER(19) NOT NULL,
    chat_room_id NUMBER(19) NOT NULL,
    manner_score NUMBER(10),
    one_line_review VARCHAR2(40 CHAR),
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_travel_companion_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_travel_companion_user FOREIGN KEY (companion_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_travel_companion_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms(id),
    CONSTRAINT uk_travel_companion_trip UNIQUE (owner_id, companion_id, chat_room_id),
    CONSTRAINT ck_travel_companion_not_self CHECK (owner_id <> companion_id),
    CONSTRAINT ck_travel_companion_manner CHECK (manner_score BETWEEN 1 AND 5)
);

CREATE INDEX ix_travel_companions_owner ON travel_companions(owner_id, created_datetime DESC);
CREATE INDEX ix_travel_companions_target_score ON travel_companions(companion_id, manner_score);
CREATE INDEX ix_travel_companions_room ON travel_companions(chat_room_id);
