CREATE TABLE user_blocks (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_id NUMBER(19) NOT NULL,
    blocked_id NUMBER(19) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_block_blocker FOREIGN KEY (blocker_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_block_blocked FOREIGN KEY (blocked_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_user_block_blocker_blocked UNIQUE (blocker_id, blocked_id),
    CONSTRAINT ck_user_block_not_self CHECK (blocker_id <> blocked_id)
);

CREATE INDEX ix_user_blocks_blocked ON user_blocks(blocked_id);
