CREATE TABLE friendships (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_user_id NUMBER(19) NOT NULL,
    second_user_id NUMBER(19) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_friendship_first_user FOREIGN KEY (first_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_friendship_second_user FOREIGN KEY (second_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_friendship_users UNIQUE (first_user_id, second_user_id),
    CONSTRAINT ck_friendship_user_order CHECK (first_user_id < second_user_id)
);

CREATE INDEX ix_friendships_second_user ON friendships(second_user_id, created_datetime DESC);

CREATE TABLE friend_requests (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id NUMBER(19) NOT NULL,
    receiver_id NUMBER(19) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_friend_request_requester FOREIGN KEY (requester_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_friend_request_receiver FOREIGN KEY (receiver_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_friend_request_users UNIQUE (requester_id, receiver_id),
    CONSTRAINT ck_friend_request_not_self CHECK (requester_id <> receiver_id)
);

CREATE INDEX ix_friend_requests_receiver ON friend_requests(receiver_id, created_datetime DESC);
CREATE INDEX ix_friend_requests_requester ON friend_requests(requester_id, created_datetime DESC);

INSERT INTO friendships (first_user_id, second_user_id, created_datetime)
SELECT follows.follower_id, follows.following_id, LEAST(follows.created_datetime, reverse_follows.created_datetime)
FROM user_follows follows
JOIN user_follows reverse_follows
  ON reverse_follows.follower_id = follows.following_id
 AND reverse_follows.following_id = follows.follower_id
WHERE follows.follower_id < follows.following_id
  AND NOT EXISTS (
      SELECT 1
      FROM user_blocks blocks
      WHERE (blocks.blocker_id = follows.follower_id AND blocks.blocked_id = follows.following_id)
         OR (blocks.blocker_id = follows.following_id AND blocks.blocked_id = follows.follower_id)
  );

INSERT INTO friend_requests (requester_id, receiver_id, created_datetime)
SELECT follows.follower_id, follows.following_id, follows.created_datetime
FROM user_follows follows
WHERE NOT EXISTS (
    SELECT 1
    FROM user_follows reverse_follows
    WHERE reverse_follows.follower_id = follows.following_id
      AND reverse_follows.following_id = follows.follower_id
)
AND NOT EXISTS (
    SELECT 1
    FROM user_blocks blocks
    WHERE (blocks.blocker_id = follows.follower_id AND blocks.blocked_id = follows.following_id)
       OR (blocks.blocker_id = follows.following_id AND blocks.blocked_id = follows.follower_id)
);

DROP TABLE user_follows CASCADE CONSTRAINTS;

ALTER TABLE notifications DROP CONSTRAINT ck_notification_type;
ALTER TABLE notifications ADD CONSTRAINT ck_notification_type CHECK (
    notification_type IN (
        'CHAT_ROOM_CREATED',
        'CHAT_MESSAGE_RECEIVED',
        'TRAVEL_COURSE_UPDATED',
        'MEETING_INFO_UPDATED',
        'RECRUITMENT_DEADLINE',
        'FRIEND_REQUEST',
        'FRIEND_ACCEPTED',
        'FEED_LIKE',
        'MARKETING'
    )
);
