CREATE TABLE user_trip_histories (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19) NOT NULL,
    original_room_id NUMBER(19) NOT NULL,
    travel_course_id NUMBER(19) NOT NULL,
    room_title VARCHAR2(100 CHAR) NOT NULL,
    room_description VARCHAR2(500 CHAR),
    trip_start_date DATE NOT NULL,
    trip_end_date DATE NOT NULL,
    host NUMBER(1) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_trip_history_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_user_trip_history_room UNIQUE (user_id, original_room_id),
    CONSTRAINT ck_user_trip_history_host CHECK (host IN (0, 1))
);

CREATE INDEX ix_user_trip_histories_user_end
    ON user_trip_histories(user_id, trip_end_date DESC, id DESC);

CREATE INDEX ix_user_trip_histories_publishable
    ON user_trip_histories(user_id, travel_course_id, host);
