CREATE TABLE agreement_terms (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term_code VARCHAR2(50 CHAR) NOT NULL,
    title VARCHAR2(100 CHAR) NOT NULL,
    is_required NUMBER(1) NOT NULL,
    content CLOB NOT NULL,
    term_version VARCHAR2(20 CHAR) NOT NULL,
    active NUMBER(1) DEFAULT 1 NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT uk_agreement_term_code_ver UNIQUE (term_code, term_version),
    CONSTRAINT ck_agreement_terms_code CHECK (term_code IN ('SERVICE', 'PRIVACY_COLLECTION', 'MARKETING')),
    CONSTRAINT ck_agreement_terms_required CHECK (is_required IN (0, 1)),
    CONSTRAINT ck_agreement_terms_active CHECK (active IN (0, 1))
);

CREATE INDEX ix_agreement_terms_active ON agreement_terms(active, id);

CREATE TABLE user_terms_agreements (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19) NOT NULL,
    agreement_term_id NUMBER(19) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_term_agreement_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_term_agreement_term FOREIGN KEY (agreement_term_id) REFERENCES agreement_terms(id),
    CONSTRAINT uk_user_term_agreement UNIQUE (user_id, agreement_term_id)
);

CREATE INDEX ix_user_term_agreements_user ON user_terms_agreements(user_id, created_datetime DESC);

INSERT INTO agreement_terms (term_code, title, is_required, content, term_version, active, created_datetime)
VALUES (
    'SERVICE',
    '[필수] 모여트립 이용약관',
    1,
    TO_CLOB(q'~# 모여트립 이용약관

## 제1조 목적

이 약관은 모여트립 서비스 운영자(이하 “회사”)와 이용자 간 서비스 이용 조건, 권리와 의무를 정하는 것을 목적으로 합니다.

## 제2조 서비스 내용

회사는 여행 모임 탐색·개설, 채팅, 여행 코스 공유, 피드와 친구 기능 등 여행 동행을 돕는 기능을 제공합니다. 서비스의 일부 기능은 운영 정책 또는 기술적 사유로 변경될 수 있습니다.

## 제3조 이용자의 의무

이용자는 관계 법령과 이 약관, 서비스 화면의 안내를 준수해야 합니다. 타인의 개인정보를 무단으로 수집·공개하거나, 불법·유해 콘텐츠를 게시하거나, 서비스 운영을 방해해서는 안 됩니다.

## 제4조 계정과 콘텐츠

이용자는 본인 계정을 안전하게 관리해야 하며, 계정에서 발생한 활동에 책임을 집니다. 이용자가 게시한 콘텐츠의 권리는 이용자에게 있으며, 회사는 서비스 제공·개선과 운영을 위해 필요한 범위에서 이를 이용할 수 있습니다.

## 제5조 이용 제한

회사는 법령 또는 운영 정책 위반, 다른 이용자의 안전을 해치는 행위가 확인되면 사전 고지 후 또는 긴급한 경우 즉시 콘텐츠 삭제, 이용 제한 등의 조치를 할 수 있습니다.

## 제6조 문의와 시행

서비스 관련 문의는 앱 내 고객 문의 채널을 이용할 수 있습니다. 이 약관의 시행일과 개정 내용은 서비스 내 공지로 안내합니다.
~'),
    '2026.08.23',
    1,
    SYSTIMESTAMP
);

INSERT INTO agreement_terms (term_code, title, is_required, content, term_version, active, created_datetime)
VALUES (
    'PRIVACY_COLLECTION',
    '[필수] 개인정보 수집 및 이용 동의',
    1,
    TO_CLOB(q'~# 개인정보 수집 및 이용 동의

모여트립은 서비스 제공을 위해 아래 개인정보를 수집·이용합니다.

| 구분 | 수집 항목 | 이용 목적 | 보유 기간 |
| --- | --- | --- | --- |
| 회원가입 | 이메일, 닉네임, 성별, 생년월일, 로그인 제공자 식별자 | 본인 확인, 회원 관리, 연령 확인 | 회원 탈퇴 또는 목적 달성 시까지 |
| 서비스 이용 | 여행 모임·채팅·피드 작성 정보, 프로필 정보 | 모임 및 커뮤니티 기능 제공, 분쟁 대응 | 회원 탈퇴 또는 목적 달성 시까지 |
| 선택 정보 | FCM 토큰 | 앱 푸시 알림 발송 | 토큰 갱신·삭제 또는 회원 탈퇴 시까지 |

## 동의 거부 권리

이용자는 개인정보 수집 및 이용에 대한 동의를 거부할 권리가 있습니다. 다만 위 필수 항목에 동의하지 않으면 회원가입과 서비스 이용이 제한됩니다.

## 보관 예외

관계 법령에 따라 보관이 필요한 정보는 해당 법령에서 정한 기간 동안 보관할 수 있습니다. 개인정보 처리의 자세한 내용은 별도 개인정보 처리방침에서 안내합니다.
~'),
    '2026.08.23',
    1,
    SYSTIMESTAMP
);

INSERT INTO agreement_terms (term_code, title, is_required, content, term_version, active, created_datetime)
VALUES (
    'MARKETING',
    '[선택] 마케팅 정보 수신 동의',
    0,
    TO_CLOB(q'~# 마케팅 정보 수신 동의

모여트립은 이벤트, 혜택, 신규 여행 코스 및 맞춤 추천 정보를 앱 푸시 등 전자적 전송 매체로 안내할 수 있습니다.

## 수신 동의와 변경

이 약관에 동의하면 마케팅 알림이 기본으로 켜집니다. 동의하지 않아도 기본 서비스 이용에는 제한이 없으며, 앱의 알림 설정에서 언제든지 마케팅 알림 수신 여부를 변경할 수 있습니다.

## 수신 거부

마케팅 정보 수신을 거부하거나 철회하면 이후 마케팅 목적의 알림을 발송하지 않습니다. 서비스 이용에 필요한 안내와 보안·운영 관련 알림은 이 동의와 별도로 발송될 수 있습니다.
~'),
    '2026.08.23',
    1,
    SYSTIMESTAMP
);
