ALTER TABLE users ADD withdrawn_datetime TIMESTAMP;

CREATE INDEX ix_users_withdrawn_datetime ON users(withdrawn_datetime);

ALTER TABLE travel_courses ADD creator_nickname VARCHAR2(24 CHAR);

UPDATE travel_courses course
SET creator_nickname = (
    SELECT users.nickname
    FROM users
    WHERE users.id = course.owner_id
)
WHERE course.type = 'PUBLIC'
  AND course.owner_id IS NOT NULL;

CREATE TABLE travel_course_likes (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_course_id NUMBER(19) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_travel_course_like_course
        FOREIGN KEY (travel_course_id) REFERENCES travel_courses(id) ON DELETE CASCADE,
    CONSTRAINT fk_travel_course_like_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_travel_course_like_course_user UNIQUE (travel_course_id, user_id)
);

CREATE INDEX ix_travel_course_likes_user ON travel_course_likes(user_id);

ALTER TABLE travel_courses DROP CONSTRAINT fk_travel_course_owner;
ALTER TABLE travel_courses ADD CONSTRAINT fk_travel_course_owner
    FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE SET NULL;
