ALTER TABLE feeds ADD hidden_by_reports NUMBER(1) DEFAULT 0 NOT NULL;

ALTER TABLE feeds ADD CONSTRAINT ck_feeds_hidden_by_reports CHECK (hidden_by_reports IN (0, 1));

CREATE TABLE feed_reports (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_id NUMBER(19) NOT NULL,
    reporter_id NUMBER(19) NOT NULL,
    reason VARCHAR2(40 CHAR) NOT NULL,
    details VARCHAR2(300 CHAR),
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_feed_report_feed FOREIGN KEY (feed_id) REFERENCES feeds(id) ON DELETE CASCADE,
    CONSTRAINT fk_feed_report_reporter FOREIGN KEY (reporter_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_feed_report_reporter UNIQUE (feed_id, reporter_id)
);

CREATE INDEX ix_feed_reports_feed ON feed_reports(feed_id);
