-- BE-12: 모집(채팅방)·멤버(사용자) 신고. 구조는 V60 feed_reports 를 그대로 따른다.
-- 신고자당 대상 1건만 남기고(중복 신고는 409), 자동 숨김·자동 차단은 하지 않는다 — 차단은 별도 API 다.
CREATE TABLE chat_room_reports (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id NUMBER(19) NOT NULL,
    reporter_id NUMBER(19) NOT NULL,
    reason VARCHAR2(40 CHAR) NOT NULL,
    details VARCHAR2(300 CHAR),
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_chat_room_report_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms(id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_room_report_reporter FOREIGN KEY (reporter_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_chat_room_report_reporter UNIQUE (chat_room_id, reporter_id)
);

CREATE INDEX ix_chat_room_reports_room ON chat_room_reports(chat_room_id);

CREATE TABLE user_reports (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reported_user_id NUMBER(19) NOT NULL,
    reporter_id NUMBER(19) NOT NULL,
    chat_room_id NUMBER(19),
    reason VARCHAR2(40 CHAR) NOT NULL,
    details VARCHAR2(300 CHAR),
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_report_reported FOREIGN KEY (reported_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_report_reporter FOREIGN KEY (reporter_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_report_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms(id) ON DELETE SET NULL,
    CONSTRAINT uk_user_report_reporter UNIQUE (reported_user_id, reporter_id)
);

CREATE INDEX ix_user_reports_reported ON user_reports(reported_user_id);
