-- 탈퇴 사유 보관. **user_id 를 두지 않는다** — 탈퇴는 「지체 없이 파기」가 원칙이라
-- 사유에 사용자 식별자를 붙이면 그 약속이 깨진다. 이탈 원인 집계에는 사유와 시각이면 충분하다
-- (QA BE-25).
CREATE TABLE user_withdrawal_reasons (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reason_code VARCHAR2(50 CHAR) NOT NULL,
    reason_detail VARCHAR2(200 CHAR),
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT ck_user_withdrawal_reason_code CHECK (
        reason_code IN (
            'TRAVEL_LESS_OFTEN',
            'NO_APPEALING_RECRUITMENT',
            'BAD_EXPERIENCE',
            'TOO_MANY_NOTIFICATIONS',
            'OTHER'
        )
    )
);

-- 기간별 집계가 이 표의 유일한 용도다.
CREATE INDEX ix_user_withdrawal_reasons_created ON user_withdrawal_reasons(created_datetime, reason_code);
