-- 댓글 신고 (BE-12). 신고 API 가 피드 전용이라 세 플랫폼이 댓글 더보기에서
-- 「아직 지원하지 않아요」 안내만 띄우고 있었다.
-- 구조는 V60 feed_reports · V6x chat_room_reports 를 그대로 따른다 — 신고자당 대상 1건, 자동 숨김 없음.
-- 사유 값은 피드 신고와 같은 FeedReportReason 을 쓴다(댓글도 「남이 쓴 글」이라 사유가 갈릴 이유가 없다).
CREATE TABLE feed_comment_reports (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id NUMBER(19) NOT NULL,
    reporter_id NUMBER(19) NOT NULL,
    reason VARCHAR2(40 CHAR) NOT NULL,
    details VARCHAR2(300 CHAR),
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_feed_comment_report_comment FOREIGN KEY (comment_id) REFERENCES feed_comments(id) ON DELETE CASCADE,
    CONSTRAINT fk_feed_comment_report_reporter FOREIGN KEY (reporter_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_feed_comment_report_reporter UNIQUE (comment_id, reporter_id)
);

CREATE INDEX ix_feed_comment_reports_comment ON feed_comment_reports(comment_id);
