ALTER TABLE users ADD manner_rating NUMBER(3, 2) DEFAULT 5.00 NOT NULL;

CREATE TABLE travel_courses (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR2(20 CHAR) NOT NULL,
    owner_id NUMBER(19),
    title VARCHAR2(100 CHAR) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    updated_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_travel_course_owner FOREIGN KEY (owner_id) REFERENCES users(id),
    CONSTRAINT ck_travel_course_type CHECK (type IN ('CUSTOM', 'MANAGED')),
    CONSTRAINT ck_travel_course_owner CHECK ((type = 'MANAGED' AND owner_id IS NULL) OR (type = 'CUSTOM' AND owner_id IS NOT NULL))
);

CREATE TABLE travel_course_places (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_course_id NUMBER(19) NOT NULL,
    place_name VARCHAR2(100 CHAR) NOT NULL,
    description VARCHAR2(300 CHAR),
    place_sequence NUMBER(10) NOT NULL,
    CONSTRAINT fk_travel_place_course FOREIGN KEY (travel_course_id) REFERENCES travel_courses(id) ON DELETE CASCADE,
    CONSTRAINT uk_travel_place_sequence UNIQUE (travel_course_id, place_sequence)
);

CREATE TABLE chat_rooms (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id NUMBER(19) NOT NULL,
    travel_course_id NUMBER(19) NOT NULL,
    room_title VARCHAR2(100 CHAR) NOT NULL,
    description VARCHAR2(500 CHAR),
    notice VARCHAR2(1000 CHAR),
    max_participants NUMBER(10) NOT NULL,
    start_date DATE NOT NULL,
    recruitment_deadline_date DATE NOT NULL,
    trip_days NUMBER(10) NOT NULL,
    day_trip_start_time TIMESTAMP,
    day_trip_end_time TIMESTAMP,
    meeting_place VARCHAR2(200 CHAR) NOT NULL,
    meeting_datetime TIMESTAMP NOT NULL,
    participation_fee NUMBER(12) NOT NULL,
    status VARCHAR2(20 CHAR) NOT NULL,
    chat_closed_datetime TIMESTAMP,
    deletion_scheduled_datetime TIMESTAMP,
    created_datetime TIMESTAMP NOT NULL,
    updated_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_chat_rooms_host FOREIGN KEY (host_id) REFERENCES users(id),
    CONSTRAINT fk_chat_rooms_course FOREIGN KEY (travel_course_id) REFERENCES travel_courses(id),
    CONSTRAINT ck_chat_rooms_capacity CHECK (max_participants BETWEEN 3 AND 20),
    CONSTRAINT ck_chat_rooms_days CHECK (trip_days BETWEEN 1 AND 30),
    CONSTRAINT ck_chat_rooms_fee CHECK (participation_fee >= 0),
    CONSTRAINT ck_chat_rooms_status CHECK (status IN ('RECRUITING', 'CONFIRMED', 'CANCELLED'))
);

CREATE TABLE chat_room_participants (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id NUMBER(19) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    role VARCHAR2(20 CHAR) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_chat_participant_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms(id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_participant_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_chat_participant_room_user UNIQUE (chat_room_id, user_id),
    CONSTRAINT ck_chat_participant_role CHECK (role IN ('HOST', 'MEMBER'))
);

CREATE TABLE chat_room_join_applications (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id NUMBER(19) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    application_message VARCHAR2(500 CHAR) NOT NULL,
    status VARCHAR2(20 CHAR) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_chat_application_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms(id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_application_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_chat_application_room_user UNIQUE (chat_room_id, user_id),
    CONSTRAINT ck_chat_application_status CHECK (status IN ('PENDING', 'WAITLISTED'))
);

CREATE TABLE chat_messages (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id NUMBER(19) NOT NULL,
    sender_id NUMBER(19),
    message_type VARCHAR2(20 CHAR) NOT NULL,
    content VARCHAR2(1000 CHAR) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_chat_message_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms(id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_message_sender FOREIGN KEY (sender_id) REFERENCES users(id),
    CONSTRAINT ck_chat_message_type CHECK (message_type IN ('USER', 'SYSTEM')),
    CONSTRAINT ck_chat_message_sender CHECK (
        (message_type = 'USER' AND sender_id IS NOT NULL) OR
        (message_type = 'SYSTEM' AND sender_id IS NULL)
    )
);

CREATE TABLE chat_room_read_statuses (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id NUMBER(19) NOT NULL,
    user_id NUMBER(19) NOT NULL,
    last_read_message_id NUMBER(19) DEFAULT 0 NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    updated_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_chat_read_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms(id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_read_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_chat_read_room_user UNIQUE (chat_room_id, user_id)
);

CREATE INDEX ix_chat_rooms_status_start ON chat_rooms(status, start_date);
CREATE INDEX ix_chat_rooms_recruitment_deadline ON chat_rooms(status, recruitment_deadline_date);
CREATE INDEX ix_chat_rooms_deletion_due ON chat_rooms(deletion_scheduled_datetime);
CREATE INDEX ix_chat_participants_room ON chat_room_participants(chat_room_id);
CREATE INDEX ix_chat_applications_queue ON chat_room_join_applications(chat_room_id, status, created_datetime, id);
CREATE INDEX ix_chat_messages_room_id ON chat_messages(chat_room_id, id);
CREATE INDEX ix_chat_read_user ON chat_room_read_statuses(user_id, chat_room_id);
