-- 기존 기본값 5.0은 평가가 없는 사용자에게 부여된 값이므로 null로 전환한다.
UPDATE users SET manner_rating = NULL;
ALTER TABLE users MODIFY (manner_rating FLOAT(53) DEFAULT NULL NULL);

-- null은 참가비가 아직 정해지지 않았음을 의미한다.
ALTER TABLE chat_rooms MODIFY (participation_fee NUMBER(19, 0) NULL);

ALTER TABLE chat_rooms ADD deletion_scheduled_date DATE;
UPDATE chat_rooms
SET deletion_scheduled_date = TRUNC(CAST(deletion_scheduled_datetime AS DATE))
WHERE deletion_scheduled_datetime IS NOT NULL;
DROP INDEX ix_chat_rooms_deletion_due;
ALTER TABLE chat_rooms DROP COLUMN deletion_scheduled_datetime;
CREATE INDEX ix_chat_rooms_deletion_due ON chat_rooms(deletion_scheduled_date);

ALTER TABLE chat_room_join_applications DROP CONSTRAINT ck_chat_application_status;
ALTER TABLE chat_room_join_applications ADD CONSTRAINT ck_chat_application_status
    CHECK (status IN ('PENDING', 'WAITLISTED', 'REJECTED'));

ALTER TABLE chat_room_join_applications DROP CONSTRAINT uk_chat_application_room_user;
CREATE INDEX ix_chat_app_user_status ON chat_room_join_applications(user_id, status, created_datetime);

ALTER TABLE chat_room_participants ADD last_read_message_id NUMBER(19) DEFAULT 0 NOT NULL;

UPDATE chat_room_participants participant
SET participant.last_read_message_id = COALESCE(
    (
        SELECT read_status.last_read_message_id
        FROM chat_room_read_statuses read_status
        WHERE read_status.chat_room_id = participant.chat_room_id
          AND read_status.user_id = participant.user_id
    ),
    0
);

DROP TABLE chat_room_read_statuses CASCADE CONSTRAINTS;

CREATE TABLE chat_room_notices (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id NUMBER(19) NOT NULL,
    author_id NUMBER(19) NOT NULL,
    content VARCHAR2(1000 CHAR),
    created_datetime TIMESTAMP NOT NULL,
    CONSTRAINT fk_chat_notice_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms(id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_notice_author FOREIGN KEY (author_id) REFERENCES users(id)
);

-- V7의 최신 공지가 있다면 최초 공지 이력으로 보존한다.
INSERT INTO chat_room_notices (chat_room_id, author_id, content, created_datetime)
SELECT id, host_id, notice, updated_datetime
FROM chat_rooms
WHERE notice IS NOT NULL;

CREATE INDEX ix_chat_notices_latest ON chat_room_notices(chat_room_id, id DESC);

ALTER TABLE chat_rooms ADD (
    meeting_latitude FLOAT(53),
    meeting_longitude FLOAT(53)
);

-- 기존 문자열 장소에서는 좌표를 역산할 수 없어 미지정 좌표로 표시한다.
UPDATE chat_rooms
SET meeting_latitude = 0.0,
    meeting_longitude = 0.0;

ALTER TABLE chat_rooms MODIFY (
    meeting_latitude NOT NULL,
    meeting_longitude NOT NULL
);

ALTER TABLE chat_rooms DROP COLUMN meeting_place;
ALTER TABLE chat_rooms DROP COLUMN notice;
