CREATE TABLE legal_dong_codes (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_code VARCHAR2(2 CHAR) NOT NULL,
    signgu_code VARCHAR2(5 CHAR) NOT NULL,
    region_name VARCHAR2(50 CHAR) NOT NULL,
    signgu_name VARCHAR2(50 CHAR) NOT NULL,
    created_datetime TIMESTAMP NOT NULL,
    updated_datetime TIMESTAMP NOT NULL,
    CONSTRAINT uk_legal_dong_region_signgu UNIQUE (region_code, signgu_code)
);

CREATE INDEX ix_legal_dong_region ON legal_dong_codes(region_code);
